export const SCORE_ACTION_TYPE = {
    SET_SCORE: "SET_SCORE",
    SET_ACTION: "SET_ACTION",
    SET_PLATER_CHOICE: "SET_PLATER_CHOICE",
    SET_OPPONENT_CHOICE: "SET_OPPONENT_CHOICE",
    SET_RESULT: "SET_RESULT"
}